{'week_start': '2026-03-01', 'week_end': '2026-03-03', 'record_count': 3, 
 'emotion_statistics': {'average_score': 0.855, 'most_common_label': 'negative', 'label_distribution': {'negative': 2, 'positive': 1}, 'trend_direction': 'improving'}, 
 'emotion_line_chart': {'chart_type': 'line', 'labels': ['2026-03-01', '2026-03-02', '2026-03-03'], 'series': [{'name': 'emotion_polarity', 'label': 'Emotion Polarity', 'type': 'line', 'data': [-0.7185929648241206, -0.98, 0.865], 'y_axis': 'emotion'}], 'markers': [{'date': '2026-03-01', 'emotion_label': 'negative', 'emotion_score': 0.7185929648241206, 'emotion_polarity': -0.7185929648241206, 'symptoms': ['肌肉僵硬', '下背痛', '位元-度量單位', '唐氏症', '創傷性傷害', '爆發', '感覺健康'], 'medications': []}, {'date': '2026-03-02', 'emotion_label': 'negative', 'emotion_score': 0.98, 'emotion_polarity': -0.98, 'symptoms': ['背痛', '睡不好', '被拋出', '是否轉彎（發現）', '感到疲倦', '易怒情緒', '疼痛', '放鬆'], 'medications': ['布洛芬']}, {'date': '2026-03-03', 'emotion_label': 'positive', 'emotion_score': 0.865, 'emotion_polarity': 0.865, 'symptoms': ['心情改善', '背痛', '肌肉會放鬆很多', '雨', '感到平靜'], 'medications': []}]}, 
 'symptom_frequency_chart': {'chart_type': 'bar', 'labels': ['背痛', '肌肉僵硬', '下背痛', '位元-度量單位', '唐氏症', '創傷性傷害', '爆發', '感覺健康', '睡不好', '被拋出'], 'series': [{'name': 'symptom_frequency', 'label': 'Symptom Frequency', 'type': 'bar', 'data': [2, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'y_axis': 'count'}], 'ranking': [{'name': '背痛', 'display': '背痛', 'count': 2}, {'name': '肌肉僵硬', 'display': '肌肉僵硬', 'count': 1}, {'name': '下背痛', 'display': '下背痛', 'count': 1}, {'name': '位元-度量單位', 'display': '位元-度量單位', 'count': 1}, {'name': '唐氏症', 'display': '唐氏症', 'count': 1}, {'name': '創傷性傷害', 'display': '創傷性傷害', 'count': 1}, {'name': '爆發', 'display': '爆發', 'count': 1}, {'name': '感覺健康', 'display': '感覺健康', 'count': 1}, {'name': '睡不好', 'display': '睡不好', 'count': 1}, {'name': '被拋出', 'display': '被拋出', 'count': 1}]}, 
 'medication_frequency_chart': {'chart_type': 'bar', 'labels': ['布洛芬'], 'series': [{'name': 'medication_frequency', 'label': 'Medication Frequency', 'type': 'bar', 'data': [1], 'y_axis': 'count'}], 'ranking': [{'name': '布洛芬', 'display': '布洛芬', 'count': 1}]}, 
 'cooccurrence_chart': {'chart_type': 'cooccurrence', 'emotion_summary': [{'emotion': 'negative', 'count': 2}, {'emotion': 'positive', 'count': 1}], 'symptom_summary': [{'symptom': '背痛', 'count': 2}, {'symptom': '肌肉僵硬', 'count': 1}, {'symptom': '下背痛', 'count': 1}, {'symptom': '位元-度量單位', 'count': 1}, {'symptom': '唐氏症', 'count': 1}, {'symptom': '創傷性傷害', 'count': 1}, {'symptom': '爆發', 'count': 1}, {'symptom': '感覺健康', 'count': 1}, {'symptom': '睡不好', 'count': 1}, {'symptom': '被拋出', 'count': 1}, {'symptom': '是否轉彎（發現）', 'count': 1}, {'symptom': '感到疲倦', 'count': 1}, {'symptom': '易怒情緒', 'count': 1}, {'symptom': '疼痛', 'count': 1}, {'symptom': '放鬆', 'count': 1}, {'symptom': '心情改善', 'count': 1}, {'symptom': '肌肉會放鬆很多', 'count': 1}, {'symptom': '雨', 'count': 1}, {'symptom': '感到平靜', 'count': 1}], 'pair_summary': [{'emotion': 'negative', 'symptom': '肌肉僵硬', 'count': 1}, {'emotion': 'negative', 'symptom': '下背痛', 'count': 1}, {'emotion': 'negative', 'symptom': '位元-度量單位', 'count': 1}, {'emotion': 'negative', 'symptom': '唐氏症', 'count': 1}, {'emotion': 'negative', 'symptom': '創傷性傷害', 'count': 1}, {'emotion': 'negative', 'symptom': '爆發', 'count': 1}, {'emotion': 'negative', 'symptom': '感覺健康', 'count': 1}, {'emotion': 'negative', 'symptom': '背痛', 'count': 1}, {'emotion': 'negative', 'symptom': '睡不好', 'count': 1}, {'emotion': 'negative', 'symptom': '被拋出', 'count': 1}, {'emotion': 'negative', 'symptom': '是否轉彎（發現）', 'count': 1}, {'emotion': 'negative', 'symptom': '感到疲倦', 'count': 1}, {'emotion': 'negative', 'symptom': '易怒情緒', 'count': 1}, {'emotion': 'negative', 'symptom': '疼痛', 'count': 1}, {'emotion': 'negative', 'symptom': '放鬆', 'count': 1}, {'emotion': 'positive', 'symptom': '心情改善', 'count': 1}, {'emotion': 'positive', 'symptom': '背痛', 'count': 1}, {'emotion': 'positive', 'symptom': '肌肉會放鬆很多', 'count': 1}, {'emotion': 'positive', 'symptom': '雨', 'count': 1}, {'emotion': 'positive', 'symptom': '感到平靜', 'count': 1}]}, 

 'symptom_severity_chart': {'chart_type': 'multi_line', 'labels': ['2026-03-01', '2026-03-02', '2026-03-03'], 'series': [{'name': '被拋出', 'display': '被拋出', 'data': [None, 1, None]}, {'name': '感覺健康', 'display': '感覺健康', 'data': [1, None, None]}, {'name': '感到疲倦', 'display': '感到疲倦', 'data': [None, 1, None]}, {'name': '睡不好', 'display': '睡不好', 'data': [None, 1, None]}, {'name': '易怒情緒', 'display': '易怒情緒', 'data': [None, 1, None]}, {'name': '肌肉會放鬆很多', 'display': '肌肉會放鬆很多', 'data': [None, None, 1]}, {'name': '創傷性傷害', 'display': '創傷性傷害', 'data': [1, None, None]}, {'name': '唐氏症', 'display': '唐氏症', 'data': [1, None, None]}, {'name': '背痛', 'display': '背痛', 'data': [None, 1, 1]}, {'name': '位元-度量單位', 'display': '位元-度量單位', 'data': [1, None, None]}, {'name': '爆發', 'display': '爆發', 'data': [1, None, None]}, {'name': '疼痛', 'display': '疼痛', 'data': [None, 1, None]}, {'name': '是否轉彎（發現）', 'display': '是否轉彎（發現）', 'data': [None, 1, None]}, {'name': '心情改善', 'display': '心情改善', 'data': [None, None, 1]}, {'name': '感到平靜', 'display': '感到平靜', 'data': [None, None, 1]}, {'name': '雨', 'display': '雨', 'data': [None, None, 1]}, {'name': '放鬆', 'display': '放鬆', 'data': [None, 1, None]}, {'name': '肌肉僵硬', 'display': '肌肉僵硬', 'data': [1, None, None]}, {'name': '下背痛', 'display': '下背痛', 'data': [3, None, None]}]}, 
 'symptom_timeline': {'chart_type': 'timeline', 'symptoms': [{'name': '肌肉僵硬', 'display': '肌肉僵硬', 'spans': [{'start': '2026-03-01', 'end': '2026-03-01', 'status': 'affirmed'}]}, {'name': '下背痛', 'display': '下背痛', 'spans': [{'start': '2026-03-01', 'end': '2026-03-01', 'status': 'affirmed'}]}, {'name': '位元-度量單位', 'display': '位元-度量單位', 'spans': [{'start': '2026-03-01', 'end': '2026-03-01', 'status': 'affirmed'}]}, {'name': '唐氏症', 'display': '唐氏症', 'spans': [{'start': '2026-03-01', 'end': '2026-03-01', 'status': 'affirmed'}]}, {'name': '創傷性傷害', 'display': '創傷性傷害', 'spans': [{'start': '2026-03-01', 'end': '2026-03-01', 'status': 'affirmed'}]}, {'name': '爆發', 'display': '爆發', 'spans': [{'start': '2026-03-01', 'end': '2026-03-01', 'status': 'affirmed'}]}, {'name': '感覺健康', 'display': '感覺健康', 'spans': [{'start': '2026-03-01', 'end': '2026-03-01', 'status': 'hypothetical'}]}, {'name': '背痛', 'display': '背痛', 'spans': [{'start': '2026-03-02', 'end': '2026-03-03', 'status': 'affirmed'}]}, {'name': '睡不好', 'display': '睡不好', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'status': 'affirmed'}]}, {'name': '被拋出', 'display': '被拋出', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'status': 'affirmed'}]}, {'name': '是否轉彎（發現）', 'display': '是否轉彎（發現）', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'status': 'affirmed'}]}, {'name': '感到疲倦', 'display': '感到疲倦', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'status': 'affirmed'}]}, {'name': '易怒情緒', 'display': '易怒情緒', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'status': 'affirmed'}]}, {'name': '疼痛', 'display': '疼痛', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'status': 'affirmed'}]}, {'name': '放鬆', 'display': '放鬆', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'status': 'affirmed'}]}, {'name': '心情改善', 'display': '心情改善', 'spans': [{'start': '2026-03-03', 'end': '2026-03-03', 'status': 'affirmed'}]}, {'name': '肌肉會放鬆很多', 'display': '肌肉會放鬆很多', 'spans': [{'start': '2026-03-03', 'end': '2026-03-03', 'status': 'affirmed'}]}, {'name': '雨', 'display': '雨', 'spans': [{'start': '2026-03-03', 'end': '2026-03-03', 'status': 'affirmed'}]}, {'name': '感到平靜', 'display': '感到平靜', 'spans': [{'start': '2026-03-03', 'end': '2026-03-03', 'status': 'affirmed'}]}]}, 
 'medication_timeline': {'chart_type': 'timeline', 'medications': [{'name': '布洛芬', 'display': '布洛芬', 'spans': [{'start': '2026-03-02', 'end': '2026-03-02', 'taken': False}]}]}, 
 'emotion_heatmap_calendar': {'chart_type': 'calendar_heatmap', 'data': [{'date': '2026-03-01', 'value': -0.7185929648241206, 'label': 'negative'}, {'date': '2026-03-02', 'value': -0.98, 'label': 'negative'}, {'date': '2026-03-03', 'value': 0.865, 'label': 'positive'}]}, 
 'cooccurrence_heatmap': {'chart_type': 'heatmap', 'x_labels': ['背痛', '肌肉僵硬', '下背痛', '位元-度量單位', '唐氏症', '創傷性傷害', '爆發', '感覺健康', '睡不好', '被拋出', '是否轉彎（發現）', '感到疲倦', '易怒情緒', '疼痛', '放鬆', '心情改善', '肌肉會放鬆很多', '雨', '感到平靜'], 'y_labels': ['positive', 'neutral', 'negative'], 'matrix': [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]], 'x_keys': ['背痛', '肌肉僵硬', '下背痛', '位元-度量單位', '唐氏症', '創傷性傷害', '爆發', '感覺健康', '睡不好', '被拋出', '是否轉彎（發現）', '感到疲倦', '易怒情緒', '疼痛', '放鬆', '心情改善', '肌肉會放鬆很多', '雨', '感到平靜']}}



[GET] Weekly Dashboard Summary:
嗨！這週辛苦囉。看了一下你這幾天的紀錄，我發現前幾天你的心情稍微有點悶悶的，不過到了週末有明顯好轉喔！以下是一些我觀察到的重點：

* 你這週的情緒趨勢是逐漸改善的，從星期一的負面情緒逐步轉變為星期三的正面情緒。
* 我注意到你這週有幾個症狀出現，像是背痛、肌肉僵硬、下背痛等，這些症狀可能與你的情緒變化有關聯。
* 看起來每當你感到心情不好時，睡眠品質就會變差，反之當你心情好時，睡眠品質也會改善。
* 我也注意到你在星期二服用了布洛芬，可能是因為背痛或其他症狀的緣故。

根據這些觀察，以下是一些小建議：

* 多喝水，保持身體水分充足，可以幫助改善睡眠品質和情緒。
* 試著提早半小時睡覺，讓身體有足夠的休息時間，可以幫助改善睡眠品質和心情。

希望這些建議能夠幫助你，記得要照顧好自己喔！